D2/final/minimorpion/main_app/urls.py
from django.urls import path

from main_app import views

app_name="main_app"

urlpatterns = [
    path('hello/', views.hello, name="hello"),
    path('play/', views.play, name="play"),
    path('save/', views.save_game, name="save"),
    path('load/', views.load_game, name="load")
]

D2/final/minimorpion/minimorpion/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    url('morpion/', include('main_app.urls'))
]

D2/final/minimorpion/main_app/models.py
from django.db import models

# Create your models here.

D2/final/minimorpion/main_app/views.py
import json

from django.shortcuts import render

from django.http import HttpResponse, JsonResponse

from .utils import Game

# Create your views here.
def hello(request):
    return HttpResponse("Salut !")


def play(request):
    player1 = request.GET.get('p1','FP')
    player2 = request.GET.get('p2','RB')
    
    return render(request, 'main_app/morpion.html',
                  {'player1': player1,
                   'player2': player2})


def save_game(request):
    game = Game(json.loads(request.POST.get('game',{})))
    game.print_game()
    game.save()
    
    return HttpResponse(status=204)    

def load_game(request):
    player1 = request.GET.get('p1','FP')
    player2 = request.GET.get('p2','RB')

    game = Game()
    
    try:
        game.load(player1, player2)
        game.print_game()
    except ObjectDoesNotExist as e:
        print(e)

    return JsonResponse(game.export_to_json(None),
                        safe=False)

D2/final/minimorpion/main_app/templates/main_app/morpion.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
  <title>Morpion</title>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'main_app/style.css' %}" />
  <script src="{% static 'main_app/jquery.min.js' %}"></script>
  <script src="{% static 'main_app/d3.v4.min.js' %}"></script>
</head>
<body>
 <h1>Match entre {{ player1 }} et {{ player2 }}</h1>
 <svg height="300" width="300" id="grille" >
 </svg>
 <form style="white-space: nowrap;" name="send"  action="javascript:send_game()">
   Envoyer la partie<br/></br>
   <input type="submit" name="send" value="Envoyer"></br>
 </form>
 <button type="button" onclick="new_game()">Nouvelle partie</button>
  <script>
    var url_save = "{% url 'main_app:save' %}" ;
    var url_load = "{% url 'main_app:load' %}" ;
    var player1 = "{{ player1 }}" ;
    var player2 = "{{ player2 }}" ;
  </script>
  <script type='text/javascript' src="{% static 'main_app/script.js' %}"></script>
</body>
</html>